# Generated by Django 5.2.8 on 2025-11-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_customuser'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE bookshelf_customuser ADD COLUMN date_of_birth DATE NULL;",
            reverse_sql="ALTER TABLE bookshelf_customuser DROP COLUMN date_of_birth;"
        ),
        migrations.RunSQL(
            "ALTER TABLE bookshelf_customuser ADD COLUMN profile_photo VARCHAR(100) NULL;",
            reverse_sql="ALTER TABLE bookshelf_customuser DROP COLUMN profile_photo;"
        ),
    ]
