# Generated by Django 5.2.8 on 2025-11-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_alter_author_name_alter_book_author_alter_book_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add new books'), ('can_change_book', 'Can edit existing books'), ('can_delete_book', 'Can delete books')]},
        ),
    ]
