# Generated by Django 5.2.8 on 2025-11-30 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The author's full name", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Authors',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='api_author_name_076641_idx')],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the book', max_length=255)),
                ('publication_year', models.IntegerField(help_text='The year the book was published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='The author of the book', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.author')),
            ],
            options={
                'verbose_name_plural': 'Books',
                'ordering': ['-publication_year', 'title'],
                'indexes': [models.Index(fields=['author', 'publication_year'], name='api_book_author__e0f153_idx'), models.Index(fields=['title'], name='api_book_title_dc9757_idx')],
            },
        ),
    ]
